### ISSUE TITLE
What kind of information can the iou tracker tracks objects during the interval in the deepstream?

### ISSUE THREAD

**Issue by YoungjaeDev** [callmesora/DeepStream-YOLO-DeepSORT#2]
Hello! 
I have a question about using deepstream iou_tracker (Interval > 0) 
I use the tracker because of the advantage that I can take the fps high, but I wonder what information the iou tracker tracks. 
The iou information is used to match id only, and I wonder how the box tracking is done.
For example KLT estimates the location of the box as a feature, and but iou wonders what information the box moves when it is interval time.

**Comment by callmesora** [comment]
I would not recommend using either of those trackers, they are just for comparision purposes. Utilize the nvdcf it has a customizable configuration file , you can tune it for faster performance (FPS) and get a better tracker than IoU. Regarding their implementation and behaviour please check NVIDIA's official documentation
